name: Deploy to Neocities
on:
  push:
    branches:
      - main # Or 'master' depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Optional: Add your build steps here if you use an SSG (e.g., npm install / npm run build)
      
      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_KEY }}
          cleanup: false
          dist_dir: public # Replace with your folder name
